package com.stori.quota.infras.dao.mapper;

import com.stori.quota.infras.dao.entity.AccountOptFlowDO;

public interface AccountOptFlowDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int insert(AccountOptFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int insertSelective(AccountOptFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    AccountOptFlowDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int updateByPrimaryKeySelective(AccountOptFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int updateByPrimaryKey(AccountOptFlowDO record);
}