package com.stori.quota.infras.dao.mapper;

import com.stori.quota.infras.dao.entity.UserAccountDO;

import java.util.List;

public interface UserAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int insert(UserAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int insertSelective(UserAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    UserAccountDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int updateByPrimaryKeySelective(UserAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Thu Jul 18 02:20:46 CST 2024
     */
    int updateByPrimaryKey(UserAccountDO record);

    UserAccountDO selectByUserId(String userId);

    UserAccountDO lockByUserIdNoWait(String userId);

    List<UserAccountDO> selectAllUsers();
}